spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:~/project
    data-username: sa
    data-password:
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE