spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:~/project
    data-username: sa
    data-password:
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true